### ISSUE TITLE
Créer Parents espace pour le titre de la pop up

### ISSUE THREAD

**Issue by lotfiAliane** [lotfiAliane/OoneSaha#1]

**Comment by ayoubensidhoum** [comment]
Je n’ai pas compris

**Comment by lotfiAliane** [comment]
F la pop up li tekhreoj pour créer un parrent le titre rah "CréerParents" raha collé dir éspace "Créer Parents"

**Comment by ayoubensidhoum** [comment]
Je ne peux pas :/
