### ISSUE TITLE
Création Parent

### ISSUE THREAD

**Issue by lotfiAliane** [lotfiAliane/OoneSaha#2]
quand on ouvre la pop up créer Parent tekhrejlek tahtha patient, ça veut dire 
on doit reselectionner le patient ? déja il est introuvable normal il est pas encore créer 

je propose pour ce problème de créer une vue spécial pour la création d'un patien ça reglera ga3 les problème relatif au patient

**Comment by lotfiAliane** [comment]
dans le cas d'une nouvelle création du patient on peut pas lui attribuer de parents 
et on s'en rend compte qu’après avoir tout saisi (ana je me suis rendu compte le medecin
le considère comme un bug)

**Comment by ayoubensidhoum** [comment]
C’est corrigé
