### ISSUE TITLE
Etat civile ---> au lieu de morte décédé 

### ISSUE THREAD

**Issue by lotfiAliane** [lotfiAliane/OoneSaha#4]

**Comment by ayoubensidhoum** [comment]
Je n’ai pas compris

**Comment by lotfiAliane** [comment]
![image](https://user-images.githubusercontent.com/18283184/49305964-1dcb3900-f4d1-11e8-83d3-1994d1b0509b.png)
au lieu li raha mort redha décédé

**Comment by ayoubensidhoum** [comment]
C'est réglé
