### ISSUE TITLE
Patient

### ISSUE THREAD

**Issue by fcbrida** [lotfiAliane/OoneSaha#6]
Masculin féminin pourquoi pas en radio box c’est plus facile

**Comment by ayoubensidhoum** [comment]
C'est réglé

**Comment by ayoubensidhoum** [comment]
Ici je peux pas parce que le champs est obligatoire
Quand je le sélectionne pas un message s'affiche machi chebab

**Comment by ayoubensidhoum** [comment]
C'est bon c'est réglé
